from ..buildgraph import build_graph4adyaSI, build_graph4adyaSI_chain, build_graph4append
from ..checker.checkers import *
from ..utils.graphs import ArgumentedPolyGraph, MultiTypeKnownGraph

# 0-Z3GSI, 1-Z3 0-1, 2-MonoSATEdgeWeight, 3-MonoSATEdgeWeight Optimzied, 4-BCGraph,
# 5-BCGraphOptimized(only cobra's 2 optimizations)
# 6-BCGraphOptimized(cobra's 2 optimizations + pruning)
# 7-strong session SI, 8-run append workload generated by Jepsen


def get_algo(algo_type):
    assert 0 <= algo_type <= 8, "Please provide a valid algo type"
    graph_cls = None
    graph_constructor = None
    checker = None

    if algo_type == 0:
        # assert False, "Not implemented yet"
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI.construct_graph_from_log
        checker = Z3GeneralSIChecker
    elif algo_type == 1:
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI.construct_graph_from_log
        checker = Z301Checker
    elif algo_type == 2:
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI.construct_graph_from_log
        checker = MonoSAT_EdgeWeightSIChecker
    elif algo_type == 3: # Note: this graph_constructor has a different API. TODO: errors when running
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI_chain.construct_graph_from_log
        checker = MonoSAT_EdgeWeightSIChecker_Optimized
    elif algo_type == 4:
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI.construct_graph_from_log
        checker = MonoBCPolyGraphChecker
    elif algo_type == 5:
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI_chain.construct_graph_from_log
        checker = MonoBCPolyGraphCheckerOptimized
        # assert False, "Not implemented yet"
    elif algo_type == 6:
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI_chain.construct_graph_from_log
        checker = MonoBCPolyGraphCheckerOptimized
    elif algo_type == 7: # strong session SI is this supported?
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4adyaSI.construct_graph_from_log
        checker = MonoBCPolyGraphChecker
    elif algo_type == 8:
        graph_cls = ArgumentedPolyGraph
        graph_constructor = build_graph4append.construct_graph_from_log
        checker = MonoBCPolyGraphCheckerOptimized

    return graph_cls, checker, graph_constructor