# docker
#PREFIX: &prefix "/Viper/history_data"
#LOG_DIR: "/Viper/history_data/logs"
#GRAPH_DIR: "/Viper/history_data/graphs"
#ANALYSIS_DIR: "/Viper/history_data/Analysis_logs"

# non-docker
PREFIX: &prefix "/home/windkl/git_repos/Viper/history_data2"
LOG_DIR: "/home/windkl/git_repos/Viper/history_data2/logs"
GRAPH_DIR: "/home/windkl/git_repos/Viper/history_data2/graphs"
ANALYSIS_DIR: "/home/windkl/git_repos/Viper/history_data2/Analysis_logs"

# local test
#PREFIX: &prefix "/home/windkl/git_repos/jepsen_data"
#LOG_DIR: "/home/windkl/git_repos/jepsen_data/jepsen_logs"
#GRAPH_DIR: "/home/windkl/git_repos/jepsen_data/graphs"
#ANALYSIS_DIR: "/home/windkl/git_repos/jepsen_data/Analysis_logs"

# the configs may be overrided by the command line args
# WORKLOAD: "rra" # range mode
# 0-false, 1-true
DEBUG: false
REGENERATE: true
#SESSION_ORDER: false
HASFINAL: false # rubis, twitter, tpcc
# --------Algorithm------
# 0-Z3GSI, 1-Z3 0-1, 2-MonoSATEdgeWeight, 3-MonoSATEdgeWeight Optimzied, 4-BCGraph,
# 5-BCGraphOptimized,
# 6-BCGraphOptimized + pruning
# 7-BE19, 8-Jepsen
ALGO: 6
